[versions]
# b: 0=alpha, 1=beta, 2=pre, 3=RC, 9=release
#                 Mmmppbvv
appVersionCode = "10800012"
appVersionName = "1.8.0-alpha.12"
#                 M.m.p-b    .v
android-compileSdk = "36"
android-minSdk = "26"
androidx-lifecycle = "2.9.6"
compose-multiplatform = "1.10.0"
android-gradle-plugin = "9.0.0"
androidx-activity-compose = "1.12.2"
androidx-core = "1.17.0"
androidx-jetpack-glance = "1.1.1"
androidx-navigation = "2.9.1"
browser = "1.9.0"
coil = "2.7.0"
google-services = "4.4.4"
firebase = "2.4.0"
google-firebase-analytics = "22.5.0"
google-firebase-crashlytics = "19.4.4"
google-firebase-database = "21.0.0"
google-firebase-auth = "23.2.1"
google-firebase-config = "22.1.2"
firebase-crashlytics-plugin = "3.0.6"
koin-compose = "4.1.1"
koin = "4.1.1"
kotlinx-datetime = "0.7.1"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0"
material3 = "1.9.0"
materialIconsExtended = "1.7.3"
runtime = "1.10.0"
supabase = "3.3.0"
semver = "3.0.0"
zoomable = "0.18.0"
ksoup = "0.2.5"
transportation-consumer = "4.0.0"
#firebase-inappmessaging-display = "21.0.1"
desugar_jdk_libs = "2.1.5"
multiplatform-settings = "1.3.0"
buildkonfig = "0.17.1"
adaptive = "1.2.0"
sqldelight = "2.2.1"
download = "5.6.0"

[libraries]
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
html-core = { module = "org.jetbrains.compose.html:html-core", version.ref = "compose-multiplatform" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
org-jetbrains-compose-ui-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose-multiplatform" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
sqldelight-primitive-adapters = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }
sqldelight-android-driver = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-web-worker-driver = { module = "app.cash.sqldelight:web-worker-driver", version.ref = "sqldelight" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-jetpack-glance = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-jetpack-glance" }
androidx-navigation-compose = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
firebase-analytics = { group = "dev.gitlive", name = "firebase-analytics", version.ref = "firebase" }
#firebase-inappmessaging-display = { module = "com.google.firebase:firebase-inappmessaging-display", version.ref = "firebase-inappmessaging-display" }
firebase-crashlytics = { group = "dev.gitlive", name = "firebase-crashlytics", version.ref = "firebase" }
firebase-database = { group = "dev.gitlive", name = "firebase-database", version.ref = "firebase" }
firebase-auth = { group = "dev.gitlive", name = "firebase-auth", version.ref = "firebase" }
firebase-config = { group = "dev.gitlive", name = "firebase-config", version.ref = "firebase" }
# TODO: remove this later
google-firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "google-firebase-analytics" }
# TODO: remove this later
google-firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "google-firebase-crashlytics" }
# TODO: remove this later
google-firebase-database = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "google-firebase-database" }
# TODO: remove this later
google-firebase-auth = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "google-firebase-auth" }
# TODO: remove this later
google-firebase-config = { group = "com.google.firebase", name = "firebase-config-ktx", version.ref = "google-firebase-config" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabase" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt", version.ref = "supabase" }
semver = { module = "io.github.z4kn4fein:semver", version.ref = "semver" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose-multiplatform" }
ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }
zoomable-image-coil = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "zoomable" }
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ksoup-network = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }
transportation-consumer = { group = "com.google.android.libraries.mapsplatform.transportation", name = "transportation-consumer", version.ref = "transportation-consumer" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
multiplatform-settings-make-observable = { module = "com.russhwolf:multiplatform-settings-make-observable", version.ref = "multiplatform-settings" }
androidx-adaptive = { group = "org.jetbrains.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }

[plugins]
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "android-gradle-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-plugin" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
download = { id = "de.undercouch.download", version.ref = "download" }